### ISSUE TITLE
Você trocou getTypes por getActions

### ISSUE THREAD

**Issue by rodrigodemacedo** [carlosrberto/parallelogram-generator#1]
No final do arquivo carlosrberto/parallelogram-generator você repetiu o getActions

ESTÁ ASSIM:
export const reducer = getReducer(counter);
export const actions = getActions(counter);
export const types = **getActions**(counter);

NÃO DEVERIA ESTAR ASSIM?
export const reducer = getReducer(counter);
export const actions = getActions(counter);
export const types = **getTypes**(counter);

À propósito, parabéns pelo artigo e pela contribuição!
https://medium.com/@carlosrberto/reduxed-redux-com-menos-boilerplate-cad046932f18

**Comment by carlosrberto** [comment]
Bem observado @rodrigodemacedo!
Só não deu erro na aplicação pois valor de `types` não estava sendo em nenhum lugar.

E que bom que curtiu o artigo. Valeu!
